version: '3.8'

services:
  mongodb:
    image: mongo:7.0.14-jammy
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
    ports:
      - "27017:27017"

